export const CHANGE_SCREEN = "CHANGE_SCREEN"
export const START_GAME = "START_GAME"
export const INPUT_MATCH = "INPUT_MATCH"
export const INPUT_DONT_MATCH = "INPUT_DONT_MATCH"
export const END_GAME = "END_GAME"
export const RESET_GAME = "RESET_GAME"

export const FETCH_SENTENCE_REQUEST = "FETCH_SENTENCE_REQUEST"
export const FETCH_SENTENCE_SUCCESS = "FETCH_SENTENCE_SUCCESS"

export const FETCH_RANKING_REQUEST = "FETCH_RANKING_REQUEST"
export const FETCH_RANKING_SUCCESS = "FETCH_RANKING_SUCCESS"
export const FETCH_ADD_RANK_REQUEST = "FETCH_ADD_RANK_REQUEST"
export const FETCH_ADD_RANK_SUCCESS = "FETCH_ADD_RANK_SUCCESS"


